"""Novos campos na tabela USER

Revision ID: 30301b1d808b
Revises: 630eb26b7c3c
Create Date: 2019-11-15 19:16:26.405446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30301b1d808b'
down_revision = '630eb26b7c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
