"""Criacao das tabelas SETOR, COMUNICADO, COMUNICADOSETOR e LOGCOMUNICADO

Revision ID: 630eb26b7c3c
Revises: 9da1e07052c0
Create Date: 2019-11-13 15:02:10.672419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630eb26b7c3c'
down_revision = '9da1e07052c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setor', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setor_setor'), 'setor', ['setor'], unique=True)
    op.create_table('comunicado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.Column('idSetorOrigem', sa.Integer(), nullable=True),
    sa.Column('dtCadastro', sa.Date(), nullable=True),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('comunicado', sa.Text(), nullable=True),
    sa.Column('apagado', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['idSetorOrigem'], ['setor.id'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comunicado_titulo'), 'comunicado', ['titulo'], unique=False)
    op.create_table('comunicado_setor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idComunicado', sa.Integer(), nullable=True),
    sa.Column('idSetor', sa.Integer(), nullable=True),
    sa.Column('hrLeitura', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['idComunicado'], ['comunicado.id'], ),
    sa.ForeignKeyConstraint(['idSetor'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_comunicado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idComunicado', sa.Integer(), nullable=True),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.Column('dtCadastro', sa.Date(), nullable=True),
    sa.Column('hrCadastro', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['idComunicado'], ['comunicado.id'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_comunicado')
    op.drop_table('comunicado_setor')
    op.drop_index(op.f('ix_comunicado_titulo'), table_name='comunicado')
    op.drop_table('comunicado')
    op.drop_index(op.f('ix_setor_setor'), table_name='setor')
    op.drop_table('setor')
    # ### end Alembic commands ###
